import { collapseProductsForDisplay } from './importer/product-dedupe.js';

const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const money=n=>Number.isFinite(Number(n))?Number(n).toLocaleString('de-DE',{style:'currency',currency:'EUR'}):'–';
const num=n=>{const v=Number(n);return Number.isFinite(v)?v:null};
const norm=s=>String(s??'').toLocaleLowerCase('de-DE').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const priceOf=o=>num(o.currentPrice??o.offerPrice??o.price);const regularOf=o=>num(o.regularPrice);const unitOf=o=>num(o.unit);
const isOffer=o=>o.isOffer===true||(num(o.offerPrice)!=null&&regularOf(o)!=null&&num(o.offerPrice)<regularOf(o));
const saving=o=>{const p=priceOf(o),r=regularOf(o);return p&&r&&r>p?Math.round((1-p/r)*100):0};
const iconFor=o=>/baby|windel|pampers/i.test(`${o.cat} ${o.name}`)?'🧸':/milch|butter|käse|joghurt/i.test(`${o.cat} ${o.name}`)?'🥛':/fleisch|wurst|fisch/i.test(`${o.cat} ${o.name}`)?'🥩':/obst|gemüse/i.test(`${o.cat} ${o.name}`)?'🥕':/getränk|wasser|saft/i.test(`${o.cat} ${o.name}`)?'🥤':/haushalt|drogerie|wasch|reiniger/i.test(`${o.cat} ${o.name}`)?'🧼':'🛒';

let rawOffers=[],displayOffers=[];let list=[];let state={q:'',type:'all',cat:'Alle Kategorien',store:'Alle Händler',sort:'smart',branchMode:'collapsed',visible:32};
const LIST_KEY='angebotsradar-list-v9';try{list=JSON.parse(localStorage.getItem(LIST_KEY)||'[]');if(!Array.isArray(list))list=[]}catch{list=[]}

function stableKey(o){return String(o.ean||o.gtin||o.canonicalProductId||o.exactMatchKey||`${o.store}|${o.name}|${o.size}`)}
function searchRank(o,query){
  const q=norm(query);if(!q)return 0;const name=norm(o.name),brand=norm(o.brand),cat=norm(o.cat),family=norm(`${o.canonicalGroup||''} ${o.canonicalProduct||''} ${o.semanticType||''} ${o.comparisonKey||''}`);let s=0;
  if(name===q)s+=5000;if(name.startsWith(q+' '))s+=2600;if(new RegExp(`(^| )${q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}( |$)`).test(name))s+=2300;if(name.includes(q))s+=900;if(family.includes(q))s+=500;if(brand.includes(q))s+=220;if(cat.includes(q))s+=80;
  for(const token of q.split(' ').filter(Boolean)){if(name.split(' ').includes(token))s+=280;else if(name.includes(token))s+=90}
  if(q==='butter'){
    const negative=/butterkeks|buttermilch|butter chicken|lip butter|body butter|butter bronzer|buttercream|butter gemuse|buttergemuse|kakaobutter|sheabutter/;
    const trueButter=/(^| )butter( |$)|markenbutter|sussrahmbutter|weidebutter|irische butter|mildgesauerte butter|fassbutter/;
    if(negative.test(name))s-=7000;else if(trueButter.test(name))s+=4200;
    if(/streichbutter|krauterbutter/.test(name))s-=350;if(/butterschmalz/.test(name))s-=900;
  }
  return s;
}
function currentRows(){return state.branchMode==='collapsed'?displayOffers:rawOffers}
function filtered(){
  const q=state.q.trim();let rows=currentRows().filter(o=>priceOf(o)!=null&&o.activeMarket!==false);
  rows=rows.filter(o=>state.cat==='Alle Kategorien'||String(o.cat||'Sonstiges')===state.cat).filter(o=>state.store==='Alle Händler'||String(o.store||'Unbekannt')===state.store);
  if(state.type==='offers')rows=rows.filter(isOffer);if(state.type==='bio')rows=rows.filter(o=>o.bio===true);if(state.type==='regular')rows=rows.filter(o=>!isOffer(o));if(q)rows=rows.filter(o=>searchRank(o,q)>0);
  rows.sort((a,b)=>{if(state.sort==='price')return (priceOf(a)??Infinity)-(priceOf(b)??Infinity);if(state.sort==='unit')return (unitOf(a)??Infinity)-(unitOf(b)??Infinity);if(state.sort==='saving')return saving(b)-saving(a)||(priceOf(a)??Infinity)-(priceOf(b)??Infinity);if(state.sort==='name')return String(a.name).localeCompare(String(b.name),'de');if(q){const d=searchRank(b,q)-searchRank(a,q);if(d)return d}if(Boolean(a.bio)!==Boolean(b.bio))return a.bio?-1:1;if(isOffer(a)!==isOffer(b))return isOffer(a)?-1:1;return saving(b)-saving(a)||(unitOf(a)??Infinity)-(unitOf(b)??Infinity)});return rows;
}
function filterCount(){return [state.cat!=='Alle Kategorien',state.store!=='Alle Händler',state.sort!=='smart',state.branchMode!=='collapsed'].filter(Boolean).length}
function updateFilterUi(){const n=filterCount();$('#filterCount').textContent=n;$('#filterCount').classList.toggle('show',n>0);$('#reset').classList.toggle('show',n>0||state.type!=='all'||state.q);$$('[data-quick]').forEach(b=>b.classList.toggle('on',b.dataset.quick===state.type));}
function renderChips(){const source=currentRows();const cats=['Alle Kategorien',...new Set(source.map(o=>String(o.cat||'Sonstiges')).filter(Boolean))].sort((a,b)=>a==='Alle Kategorien'?-1:b==='Alle Kategorien'?1:a.localeCompare(b,'de'));const stores=['Alle Händler',...new Set(source.map(o=>String(o.store||'Unbekannt')).filter(Boolean))].sort((a,b)=>a==='Alle Händler'?-1:b==='Alle Händler'?1:a.localeCompare(b,'de'));$('#cats').innerHTML=cats.map(x=>`<button class="chip ${x===state.cat?'on':''}" data-cat="${esc(x)}" type="button">${esc(x)}</button>`).join('');$('#stores').innerHTML=stores.map(x=>`<button class="chip ${x===state.store?'on':''}" data-store="${esc(x)}" type="button">${esc(x)}</button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;state.visible=32;renderChips();render()});$$('[data-store]').forEach(b=>b.onclick=()=>{state.store=b.dataset.store;state.visible=32;renderChips();render()})}
function branchesMeta(o){const count=Number(o.branchCount||o.markets?.length||1);return count>1?`<span class="pill branches">${count} Filialen</span>`:''}
function card(o){const p=priceOf(o),r=regularOf(o),u=unitOf(o),save=saving(o),key=stableKey(o),added=list.some(x=>x.key===key),img=o.image||o.imageUrl||'';const branchCount=Number(o.branchCount||o.markets?.length||1);return `<article class="product ${isOffer(o)?'offer':''}"><div class="thumb">${img?`<img src="${esc(img)}" alt="" loading="lazy" onerror="this.parentNode.textContent='${iconFor(o)}'">`:iconFor(o)}</div><div class="productBody"><div class="topline"><span class="pill">${esc(o.store||'Markt')}</span>${isOffer(o)?'<span class="pill offer">ANGEBOT</span>':''}${o.bio?'<span class="pill bio">BIO</span>':''}${branchesMeta(o)}</div><h3>${esc(o.name||'Produkt')}</h3><div class="meta">${[o.brand,o.size,branchCount===1?o.market:null].filter(Boolean).map(esc).join(' · ')}</div><div class="actions"><button class="add ${added?'added':''}" data-add="${esc(key)}" type="button">${added?'✓ Auf Liste':'+ Liste'}</button><button class="detail" data-detail="${esc(key)}" type="button">Preisdetails</button></div></div><div class="price">${r&&p&&r>p?`<div class="old">${money(r)}</div>`:''}<div class="now">${money(p)}</div>${branchCount>1?'<div class="from">bester Filialpreis</div>':''}${u?`<div class="unit">${money(u)} ${esc(o.unitLabel||'')}</div>`:''}${save?`<div class="saving">-${save}%</div>`:''}</div></article>`}
function renderDeals(){if(state.q){$('#dealSection').hidden=true;return}const seen=new Set();const rows=[];for(const o of displayOffers.filter(x=>isOffer(x)&&priceOf(x)!=null).sort((a,b)=>saving(b)-saving(a)||(unitOf(a)??Infinity)-(unitOf(b)??Infinity))){const k=`${o.store}|${stableKey(o)}`;if(seen.has(k))continue;seen.add(k);rows.push(o);if(rows.length===6)break}$('#deals').innerHTML=rows.map(o=>`<article class="deal offer"><div class="dealTop"><span class="store">${esc(o.store||'Markt')}</span><span class="dealBadge">${saving(o)?`-${saving(o)}%`:'ANGEBOT'}</span></div><h3>${esc(o.name||'Produkt')}</h3><div class="dealMeta">${[o.size,Number(o.branchCount)>1?`${o.branchCount} Filialen`:o.market].filter(Boolean).map(esc).join(' · ')}</div><div class="dealBottom"><div class="dealPrice">${money(priceOf(o))}</div><div class="dealUnit">${unitOf(o)?`${money(unitOf(o))}<br>${esc(o.unitLabel||'')}`:''}</div></div></article>`).join('');$('#dealSection').hidden=!rows.length}
function render(){updateFilterUi();const rows=filtered();const shown=rows.slice(0,state.visible);$('#products').innerHTML=shown.length?shown.map(card).join(''):`<div class="empty"><strong>Keine passenden Produkte gefunden</strong>Versuche einen allgemeineren Suchbegriff oder entferne einen Filter.</div>`;$('#resultsTitle').textContent=state.q?`Ergebnisse für „${state.q}“`:'Preisvergleich';$('#resultsSubtitle').textContent=state.q?'Nach Relevanz sortiert – echte Produkttreffer zuerst':'Produkte aus deinen lokalen Märkten';$('#resultInfo').textContent=`${rows.length.toLocaleString('de-DE')} Treffer`;$('#more').hidden=rows.length<=state.visible;$('#more').textContent=`Mehr anzeigen · ${Math.min(rows.length-state.visible,32)} weitere`;$$('[data-add]').forEach(b=>b.onclick=()=>toggleList(b.dataset.add));$$('[data-detail]').forEach(b=>b.onclick=()=>openDetails(b.dataset.detail));renderDeals()}
function saveList(){localStorage.setItem(LIST_KEY,JSON.stringify(list));$('#listCount').textContent=list.length}
function toggleList(key){const i=list.findIndex(x=>x.key===key);if(i>=0)list.splice(i,1);else{const o=currentRows().find(x=>stableKey(x)===key);if(o)list.push({key,name:o.name,store:o.store,market:o.market,size:o.size,price:priceOf(o),branchCount:o.branchCount||1})}saveList();render();if($('#listBack').classList.contains('open'))renderList()}
function renderList(){if(!list.length){$('#listItems').innerHTML='<div class="listEmpty">Noch nichts auf der Liste.</div>';$('#listSummary').innerHTML='';return}$('#listItems').innerHTML=list.map(x=>`<div class="listItem"><div><b>${esc(x.name)}</b><small>${[x.store,x.size,Number(x.branchCount)>1?`${x.branchCount} Filialen`:x.market].filter(Boolean).map(esc).join(' · ')}</small></div><div><div class="listPrice">${money(x.price)}</div><button class="remove" data-remove="${esc(x.key)}" type="button">Entfernen</button></div></div>`).join('');const total=list.reduce((s,x)=>s+(num(x.price)||0),0);$('#listSummary').innerHTML=`<div class="summary"><strong>${money(total)}</strong><br>${list.length} Produkte · ${new Set(list.map(x=>x.store)).size} Händler</div>`;$$('[data-remove]').forEach(b=>b.onclick=()=>{list=list.filter(x=>x.key!==b.dataset.remove);saveList();renderList();render()})}
function openBack(id){$('#'+id).classList.add('open');$('#'+id).setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeBack(id){$('#'+id).classList.remove('open');$('#'+id).setAttribute('aria-hidden','true');document.body.style.overflow=''}
function openDetails(key){const o=currentRows().find(x=>stableKey(x)===key);if(!o)return;const p=priceOf(o),r=regularOf(o),u=unitOf(o),s=saving(o);const markets=Array.isArray(o.markets)?o.markets:[];$('#detailContent').innerHTML=`<div class="detailBox"><h3>${esc(o.name||'Produkt')}</h3><p>${[o.brand,o.size,o.store].filter(Boolean).map(esc).join(' · ')}</p><div class="detailStats"><div class="detailStat"><b>${money(p)}</b><span>aktueller Preis</span></div><div class="detailStat"><b>${r?money(r):'–'}</b><span>regulärer Preis</span></div><div class="detailStat"><b>${s?`${s}%`:'–'}</b><span>Ersparnis</span></div></div>${u?`<p><b>Grundpreis:</b> ${money(u)} ${esc(o.unitLabel||'')}</p>`:''}${markets.length>1?`<div class="branchesList"><p><b>Verfügbare Filialen</b></p>${markets.map(m=>`<div class="branchRow"><span>${esc(m.market||m.address||'Filiale')}</span><span>${m.price?money(m.price):''}</span></div>`).join('')}</div>`:`<p><b>Filiale:</b> ${esc(o.market||'–')}<br>${esc(o.address||'')}</p>`}<p>Preisverlauf und historische Vergleichswerte werden für dieses Produkt fortlaufend gespeichert.</p></div>`;openBack('detailBack')}
async function loadCommit(){try{const r=await fetch('https://api.github.com/repos/SebMut/Einkaufsliste/commits/main',{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();const sha=String(d.sha||'');if(sha){$('#commitBadge').textContent=`Commit ${sha.slice(0,8)}`;$('#commitBadge').href=`https://github.com/SebMut/Einkaufsliste/commit/${sha}`;$('#commitBadge').title=`Aktueller main-Commit: ${sha}`}}catch{$('#commitBadge').textContent='Commit ?'}}
async function load(){try{const r=await fetch(`./data/offers-live.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();rawOffers=(Array.isArray(d.offers)?d.offers:[]).filter(o=>o&&o.name&&priceOf(o)!=null&&o.activeMarket!==false);displayOffers=collapseProductsForDisplay(rawOffers);const generated=d.generatedAt?new Date(d.generatedAt):null;const stamp=generated&&!Number.isNaN(generated.getTime())?generated.toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'}):'aktuell';const hidden=rawOffers.length-displayOffers.length;$('#dot').className='dot ok';$('#dataStatus').textContent=`Stand ${stamp} · ${displayOffers.length.toLocaleString('de-DE')} sichtbare Produkte${hidden>0?` · ${hidden.toLocaleString('de-DE')} Dubletten/Filialtreffer gebündelt`:''}`;renderChips();render()}catch(e){console.error(e);$('#dot').className='dot warn';$('#dataStatus').textContent='Produktdaten konnten gerade nicht geladen werden.';$('#products').innerHTML='<div class="empty"><strong>Daten momentan nicht verfügbar</strong>Bitte Seite später erneut laden.</div>'}}
$$('[data-quick]').forEach(b=>b.onclick=()=>{state.type=b.dataset.quick;state.visible=32;render()});$('#q').oninput=e=>{state.q=e.target.value;state.visible=32;render()};$('#sort').onchange=e=>{state.sort=e.target.value;render()};$('#branchMode').onchange=e=>{state.branchMode=e.target.value;state.visible=32;state.cat='Alle Kategorien';state.store='Alle Händler';renderChips();render()};$('#filterBtn').onclick=()=>{const f=$('#filters');f.classList.toggle('open');$('#filterBtn').classList.toggle('on',f.classList.contains('open'))};$('#reset').onclick=()=>{state={q:'',type:'all',cat:'Alle Kategorien',store:'Alle Händler',sort:'smart',branchMode:'collapsed',visible:32};$('#q').value='';$('#sort').value='smart';$('#branchMode').value='collapsed';renderChips();render()};$('#more').onclick=()=>{state.visible+=32;render()};$('#openList').onclick=()=>{renderList();openBack('listBack')};$('#clearList').onclick=()=>{list=[];saveList();renderList();render()};$$('[data-close]').forEach(b=>b.onclick=()=>closeBack(b.dataset.close));$$('.back').forEach(b=>b.onclick=e=>{if(e.target===b)closeBack(b.id)});document.onkeydown=e=>{if(e.key==='Escape')$$('.back.open').forEach(b=>closeBack(b.id))};
saveList();loadCommit();load();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
