import * as cheerio from 'cheerio';
import fs from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(process.cwd(), '..');
const markets = JSON.parse(await fs.readFile(path.join(ROOT, 'data/markets.json'), 'utf8'));
const file = path.join(ROOT, 'data/offers-live.json');
const data = JSON.parse(await fs.readFile(file, 'utf8'));
const now = new Date().toISOString();

const KEY_RULES = [
  ['Windeln', /\bwindel(?:n|hose)?\b|pants\b/i], ['Feuchttücher', /feucht(?:e)?tücher|wipes\b/i],
  ['Babymilch', /\b(?:pre|anfangs|folge|kinder)milch\b|säuglingsnahrung|milchnahrung/i],
  ['Babybrei', /babybrei|getreidebrei|milchbrei/i], ['Babygläschen', /babygläschen|gläschen|beikost/i],
  ['Butter', /\bbutter\b/i], ['Milch', /\b(?:vollmilch|frischmilch|h-?milch)\b/i], ['Eier', /\beier\b/i],
  ['Bananen', /\bbananen?\b/i], ['Äpfel', /\bäpfel|apfel\b/i], ['Tomaten', /tomaten?|rispentomaten/i],
  ['Paprika', /\bpaprika\b/i], ['Gurken', /gurken?|salatgurke/i], ['Kartoffeln', /kartoffeln?/i],
  ['Hackfleisch', /hackfleisch|rinderhack|schweinehack/i], ['Hähnchen', /hähnchen|huhn|chicken/i],
  ['Rindfleisch', /rind(?:er)?|jungbullen|steak/i], ['Schweinefleisch', /schwein|schnitzel/i],
  ['Lachs', /\blachs\b/i], ['Fisch', /fisch|dorade|forelle/i], ['Joghurt', /joghurt|yoghurt|kefir/i],
  ['Käse', /käse|gouda|emmentaler|mozzarella|frischkäse/i], ['Kaffee', /kaffee|caff[eè]|espresso/i],
  ['Nudeln', /nudeln|pasta|spaghetti|penne/i], ['Reis', /\breis\b/i], ['Mehl', /\bmehl\b/i],
  ['Öl', /öl|olivenöl|rapsöl|sonnenblumenöl/i], ['Pizza', /\bpizza\b/i], ['Brot', /\bbrot\b/i],
  ['Brötchen', /brötchen|semmel|breze/i], ['Wurst', /wurst|salami|schinken/i],
  ['Mineralwasser', /mineralwasser|wasser\s+(?:medium|still|classic)/i], ['Saft', /saft|nektar/i],
  ['Cola', /cola|coca-cola|pepsi/i], ['Bier', /bier|pils|helles|weißbier/i],
  ['Schokolade', /schokolade|schoko/i], ['Chips', /chips|snack/i], ['Eis', /eiscreme|speiseeis/i]
];
const BABY = /baby|pampers|windel|pants|feuchttücher|wickel|schnuller|säugling|beikost|anfangsmilch|folgemilch|pre\b|gläschen/i;
const FOOD = /kg|\bg\b|liter|\bl\b|ml|stück|pack|becher|flasche|dose|obst|gemüse|fleisch|fisch|milch|käse|butter|joghurt|kaffee|nudel|reis|brot|wurst|getränk|bio|schokolade|eier|pizza|tomat|banane|apfel|äpfel/i;
const REJECT = /werkzeug|akku|shirt|hose|socke|möbel|lampe|spielzeug|garten|handtuch|bohrer|pfanne|topf|geschirr|make-?up|parfüm|haarfarbe|katzen|hunde|waschmittel/i;
const ICONS = {'Baby & Kleinkind':'👶','Obst & Gemüse':'🥦','Milchprodukte':'🥛','Fleisch & Fisch':'🥩','Kaffee & Frühstück':'☕','Vorrat':'🍝','Tiefkühl':'🧊','Getränke':'🥤','Süßes & Snacks':'🍫','Backwaren':'🥖','Lebensmittel':'🛒'};

const norm = s => String(s ?? '').replace(/\u00a0/g,' ').replace(/[ \t]+/g,' ').replace(/\n\s*/g,'\n').trim();
function number(v){let t=String(v??'').replace(/\s/g,'').replace(/[€*]/g,'');if(t.includes(',')&&t.includes('.')){if(t.lastIndexOf(',')>t.lastIndexOf('.'))t=t.replace(/\./g,'').replace(',','.');else t=t.replace(/,/g,'');}else if(t.includes(','))t=t.replace(',','.');return Number(t)}
function relevant(t,source){t=norm(t);if(source.mode==='baby')return BABY.test(t);if(REJECT.test(t)&&!BABY.test(t))return false;return FOOD.test(t)||BABY.test(t)||KEY_RULES.some(([,r])=>r.test(t));}
function keyOf(t,name){for(const[k,r]of KEY_RULES)if(r.test(t))return k;return name.replace(/\b(?:bio|aktion|knaller|superknüller|angebot|je|packung)\b/ig,'').replace(/\s+/g,' ').trim().slice(0,55)}
function category(t){if(BABY.test(t))return'Baby & Kleinkind';if(/banane|apfel|äpfel|tomat|paprika|gurke|kartoff|zwiebel|möhre|karotte|beeren|trauben|avocado/i.test(t))return'Obst & Gemüse';if(/milch|butter|joghurt|quark|käse|gouda|mozzarella|sahne/i.test(t))return'Milchprodukte';if(/hack|rind|schwein|hähnchen|pute|wurst|salami|schinken|lachs|fisch|steak|schnitzel/i.test(t))return'Fleisch & Fisch';if(/kaffee|espresso|tee|hafer|müsli|eier/i.test(t))return'Kaffee & Frühstück';if(/nudel|pasta|reis|mehl|zucker|öl|pesto/i.test(t))return'Vorrat';if(/tiefkühl|pizza|pommes|eiscreme/i.test(t))return'Tiefkühl';if(/wasser|cola|saft|nektar|limonade|bier|wein|sekt/i.test(t))return'Getränke';if(/schokolade|keks|chips|snack|bonbon/i.test(t))return'Süßes & Snacks';if(/brot|brötchen|semmel|breze|baguette/i.test(t))return'Backwaren';return'Lebensmittel'}
function sizeOf(t){const m=norm(t).match(/(?:je\s+)?((?:\d+\s*[x×]\s*)?\d+(?:[.,]\d+)?\s*(?:kg|g|l|ml|Stück|St\.?|Pckg\.?|Packung|Becher|Dose|Fl\.?|Netz|Schale))/i);return m?m[1]:'Packung'}
function baseOf(t,price,size){let m=norm(t).match(/(?:1\s*)?(kg|l|Stück|St\.?)\s*(?:=|:)\s*(\d+[.,]\d{2})/i);if(m)return{unit:number(m[2]),label:/kg/i.test(m[1])?'€/kg':/l/i.test(m[1])?'€/l':'€/Stk.'};m=norm(t).match(/(\d+[.,]\d{2})\s*\/\s*(kg|l|Stück|St\.?)/i);if(m)return{unit:number(m[1]),label:/kg/i.test(m[2])?'€/kg':/l/i.test(m[2])?'€/l':'€/Stk.'};m=size.match(/(\d+)\s*[x×]\s*(\d+(?:[.,]\d+)?)\s*(g|kg|ml|l)/i);if(m){const q=number(m[1])*number(m[2]),u=m[3].toLowerCase();if(u==='g')return{unit:price/(q/1000),label:'€/kg'};if(u==='kg')return{unit:price/q,label:'€/kg'};if(u==='ml')return{unit:price/(q/1000),label:'€/l'};return{unit:price/q,label:'€/l'}}m=size.match(/(\d+(?:[.,]\d+)?)\s*(kg|g|l|ml|Stück|St\.?)/i);if(m){const q=number(m[1]),u=m[2].toLowerCase();if(u==='g')return{unit:price/(q/1000),label:'€/kg'};if(u==='kg')return{unit:price/q,label:'€/kg'};if(u==='ml')return{unit:price/(q/1000),label:'€/l'};if(u==='l')return{unit:price/q,label:'€/l'};return{unit:price/q,label:'€/Stk.'}}return{unit:price,label:'€/Packung'}}
function cleanName(s){return norm(s).replace(/^Angebot:\s*/i,'').replace(/^(?:AKTION|KNALLER|SUPERKNÜLLER)\s+/i,'').trim().slice(0,140)}
function validName(n){return n.length>=3&&/[A-Za-zÄÖÜäöüß]{3}/.test(n)&&!/^\d|^(?:angebot|aktion|filiale|image|grundpreis|zu den angeboten)$/i.test(n)&&!/datenschutz|newsletter|öffnungszeiten|filialen in der nähe|stellenangebote/i.test(n)}
function salePrice(store,t){let m;if(store==='EDEKA'&&(m=t.match(/Festpreis von\s*(\d+[.,]\d{2})\s*€/i)))return number(m[1]);if(store==='REWE'&&(m=t.match(/(?:Aktion|Knaller)\s*(\d+[.,]\d{2})\s*€/i)))return number(m[1]);if(store==='Netto'){if((m=t.match(/(?:UVP|statt)\s*(\d+[.,]\d{2})\s+(\d+[.,]\d{2})\*?/i)))return number(m[2]);if((m=t.match(/(?:Aktion|Dauertiefpreis|nur)\s*(\d+[.,]\d{2})\*?/i)))return number(m[1]);}if((m=t.match(/(?:Aktionspreis|Angebotspreis|Festpreis von|nur)\s*(\d+[.,]\d{2})\s*€?/i)))return number(m[1]);const labelled=t.match(/(?:Aktion|Knaller|Superknüller)[\s\S]{0,40}?(\d+[.,]\d{2})\s*€/i);if(labelled)return number(labelled[1]);return NaN}
function makeOffer(source,block,name,price){name=cleanName(name);if(!validName(name)||!Number.isFinite(price)||price<=.05||price>=500||!relevant(`${name} ${block}`,source))return null;const size=sizeOf(block),base=baseOf(block,price,size),cat=category(`${name} ${block}`);return{key:keyOf(`${name} ${block}`,name),name,store:source.store,market:source.market,address:source.address,cat,size,price:+price.toFixed(2),unit:+base.unit.toFixed(3),unitLabel:base.label,icon:ICONS[cat]||'🛒',bio:/\bbio\b|bioland|naturland|demeter|öko-/i.test(`${name} ${block}`),app:/app-?preis/i.test(block),coupon:/coupon|xtra/i.test(block),advertised:/angebot|aktion|knaller|werbung|uvp|statt/i.test(block),sourceUrl:source.url,sourceScope:source.scope,importedAt:now}}
function candidateName(block,heading=''){if(validName(cleanName(heading))&&relevant(heading+' '+block,{mode:null}))return cleanName(heading);const lines=norm(block).split('\n').map(cleanName).filter(Boolean);for(const line of lines){if(validName(line)&&relevant(line+' '+block,{mode:null})&&!/^(?:Filiale|Image|Gültig|Aktion|Knaller|Superknüller|UVP|statt|nur)/i.test(line))return line}return''}
function blocksFromHtml(html){const $=cheerio.load(html);$('script,style,noscript,svg').remove();const out=[];const seen=new Set();const add=(heading,text)=>{text=norm(text);if(text.length<10||text.length>6000)return;const k=text.slice(0,500);if(seen.has(k))return;seen.add(k);out.push({heading:cleanName(heading),text})};$('h2,h3,h4,h5').each((_,el)=>{const h=$(el),heading=h.text();let p=h;for(let d=0;d<7;d++){p=p.parent();if(!p.length)break;const text=p.text();if(/\d+[.,]\d{2}\s*€|UVP|statt|Festpreis von|Aktion|Knaller|Dauertiefpreis/i.test(text)&&text.length<6000){add(heading,text);break}}});$('article,li,[class*="offer" i],[class*="product" i],[class*="card" i],[class*="tile" i],[class*="slide" i]').each((_,el)=>add('',$(el).text()));return{$,out}}
async function download(url){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),18000);try{const r=await fetch(url,{redirect:'follow',signal:controller.signal,headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/149 Safari/537.36','accept':'text/html,application/xhtml+xml','accept-language':'de-DE,de;q=0.9,en;q=0.6','cache-control':'no-cache'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(timer)}}
async function fallbackSource(source){try{const html=await download(source.url);const {out}=blocksFromHtml(html);const offers=[];for(const b of out){const price=salePrice(source.store,b.text);if(!Number.isFinite(price))continue;const name=candidateName(b.text,b.heading);const o=makeOffer(source,b.text,name,price);if(o)offers.push(o)}const map=new Map();for(const o of offers){const k=[o.name.toLowerCase(),o.size,o.price].join('|');if(!map.has(k))map.set(k,o)}return{offers:[...map.values()].slice(0,250),htmlBytes:html.length,blocks:out.length}}catch(e){return{offers:[],error:String(e.message||e),htmlBytes:0,blocks:0}}}

const existing=new Map();for(const o of data.offers||[]){existing.set([o.store,o.market,String(o.name).toLowerCase(),o.size,o.price].join('|'),o)}
for(const source of markets.sources){const status=(data.sources||[]).find(s=>s.store===source.store&&s.market===source.market);if(!status||status.count>=5)continue;console.log(`HTTP-Fallback ${source.store} ...`);const r=await fallbackSource(source);for(const o of r.offers)existing.set([o.store,o.market,o.name.toLowerCase(),o.size,o.price].join('|'),o);if(r.offers.length){status.status='ok';status.count=(status.count||0)+r.offers.length;status.message=`${status.count} Angebote inkl. HTTP-Fallback (${r.offers.length} ergänzt)`;}else if(status.status!=='ok'){status.message=`Browser ohne Treffer; HTTP-Fallback ebenfalls 0 (HTML ${r.htmlBytes} Bytes / ${r.blocks} Blöcke${r.error?` / ${r.error}`:''})`;}}
const offers=[...existing.values()].sort((a,b)=>String(a.key).localeCompare(String(b.key),'de')||Number(!!b.bio)-Number(!!a.bio)||Number(a.unit)-Number(b.unit));offers.forEach((o,i)=>o.id=i+1);data.offers=offers;data.offerCount=offers.length;data.httpFallbackAt=now;await fs.writeFile(file,JSON.stringify(data,null,2)+'\n');console.log(`HTTP-Fallback fertig: ${offers.length} Gesamtangebote.`);
