import fs from 'node:fs/promises';
import path from 'node:path';
const ROOT=path.resolve(process.cwd(),'..');
const markets=JSON.parse(await fs.readFile(path.join(ROOT,'data/markets.json'),'utf8'));
const file=path.join(ROOT,'data/offers-live.json');
const data=JSON.parse(await fs.readFile(file,'utf8'));
const source=markets.sources.find(x=>x.store==='Netto');
const status=(data.sources||[]).find(x=>x.store==='Netto'&&x.market===source?.market);
if(!source||!status||status.count>=5)process.exit(0);
const now=new Date().toISOString();
const norm=s=>String(s??'').replace(/\r/g,'').replace(/\u00a0/g,' ').replace(/[ \t]+/g,' ').trim();
const n=v=>Number(String(v??'').replace(',','.').replace(/[^0-9.]/g,''));
const KEYS=[['Butter',/butter/i],['Milch',/milch/i],['Eier',/\beier\b/i],['Bananen',/bananen?/i],['Äpfel',/äpfel|apfel/i],['Tomaten',/tomaten?/i],['Paprika',/paprika/i],['Möhren',/möhren|karotten/i],['Brot',/brot/i],['Brötchen',/breze|brötchen|semmel/i],['Fisch',/fisch|lachs/i],['Joghurt',/joghurt|activia/i],['Käse',/käse|grillkäse|gouda|mozzarella/i],['Pizza',/pizza/i],['Saft',/saft|nektar/i],['Cola',/coca-cola|cola|fanta/i],['Energy Drink',/energy drink|rockstar/i],['Schokolade',/knoppers|schokolade|nutella/i],['Baby-Snacks',/milupa|baby.*snack/i],['Feuchttücher',/feuchttücher/i]];
const FOOD=/kg|\bg\b|ml|\bl\b|stück|milch|butter|eier|banane|apfel|äpfel|tomat|möhren|brot|breze|fisch|joghurt|käse|pizza|saft|cola|energy|knoppers|nutella|milupa|feuchttücher|bio/i;
function keyOf(t,name){for(const[k,r]of KEYS)if(r.test(t))return k;return name.slice(0,55)}
function cat(t){if(/banane|apfel|äpfel|tomat|möhren|karotten|orangen/i.test(t))return'Obst & Gemüse';if(/milch|butter|joghurt|käse/i.test(t))return'Milchprodukte';if(/fisch|fleisch|wurst/i.test(t))return'Fleisch & Fisch';if(/pizza|tiefgekühlt|eis/i.test(t))return'Tiefkühl';if(/saft|cola|energy|wasser/i.test(t))return'Getränke';if(/baby|milupa|feuchttücher/i.test(t))return'Baby & Kleinkind';if(/brot|breze|brötchen/i.test(t))return'Backwaren';return'Lebensmittel'}
function icon(c){return {'Obst & Gemüse':'🥦','Milchprodukte':'🥛','Fleisch & Fisch':'🥩','Tiefkühl':'🧊','Getränke':'🥤','Baby & Kleinkind':'👶','Backwaren':'🥖'}[c]||'🛒'}
function sizeOf(t){const m=t.match(/((?:\d+\s*[x×]\s*)?\d+(?:[.,]\d+)?\s*(?:kg|g|l|ml|Stück))/i);return m?m[1]:'Packung'}
function base(t,p,size){let m=t.match(/(\d+[.,]\d{1,2})\s*\/\s*(kg|l)/i);if(m)return{u:n(m[1]),l:/kg/i.test(m[2])?'€/kg':'€/l'};m=size.match(/(\d+)\s*[x×]\s*(\d+(?:[.,]\d+)?)\s*(g|kg|ml|l)/i);if(m){const q=n(m[1])*n(m[2]),u=m[3].toLowerCase();return u==='g'?{u:p/(q/1000),l:'€/kg'}:u==='kg'?{u:p/q,l:'€/kg'}:u==='ml'?{u:p/(q/1000),l:'€/l'}:{u:p/q,l:'€/l'}}m=size.match(/(\d+(?:[.,]\d+)?)\s*(kg|g|l|ml|Stück)/i);if(m){const q=n(m[1]),u=m[2].toLowerCase();return u==='g'?{u:p/(q/1000),l:'€/kg'}:u==='kg'?{u:p/q,l:'€/kg'}:u==='ml'?{u:p/(q/1000),l:'€/l'}:u==='l'?{u:p/q,l:'€/l'}:{u:p/q,l:'€/Stk.'}}return{u:p,l:'€/Packung'}}
function currentPrice(block){let m=block.match(/(?:UVP|statt)\s*(\d+[.,]\d{2})\s+(\d+[.,]\d{2})\*?/i);if(m)return n(m[2]);m=block.match(/(?:Aktion|Dauertiefpreis)\s*(\d+[.,]\d{2})\*?/i);if(m)return n(m[1]);m=block.match(/\bnur\s*[\s\S]{0,40}?(\d+[.,]\d{2})\*?/i);if(m)return n(m[1]);return NaN}
const r=await fetch('https://r.jina.ai/'+source.url,{headers:{accept:'text/plain','user-agent':'AngebotsRadar/4.2'}});if(!r.ok)throw new Error('Netto Reader HTTP '+r.status);const md=await r.text();const lines=md.split('\n').map(norm).filter(Boolean);const offers=[];
for(let i=0;i<lines.length;i++){const name=lines[i].replace(/^[-*]\s*/,'').replace(/^\[Input\]\s*/,'');if(name.length<5||name.length>130||!FOOD.test(name)||/Filiale|Image|Zu den Angeboten|Grundpreis|Stellenangebote|Filial-Angebote/i.test(name))continue;const block=lines.slice(i,Math.min(lines.length,i+10)).join('\n');const price=currentPrice(block);if(!Number.isFinite(price)||price<=.05||price>100)continue;const size=sizeOf(name+' '+block),bp=base(block,price,size),c=cat(name+' '+block);offers.push({key:keyOf(name+' '+block,name),name,store:source.store,market:source.market,address:source.address,cat:c,size,price:+price.toFixed(2),unit:+bp.u.toFixed(3),unitLabel:bp.l,icon:icon(c),bio:/\bbio\b/i.test(name+' '+block),app:false,coupon:false,advertised:true,sourceUrl:source.url,sourceScope:source.scope,sourceTransport:'reader',importedAt:now});}
const seen=new Map();for(const o of offers){const k=[o.name.toLowerCase(),o.size,o.price].join('|');if(!seen.has(k))seen.set(k,o)}const clean=[...seen.values()].slice(0,200);const all=new Map();for(const o of data.offers||[])all.set([o.store,o.market,String(o.name).toLowerCase(),o.size,o.price].join('|'),o);for(const o of clean)all.set([o.store,o.market,o.name.toLowerCase(),o.size,o.price].join('|'),o);data.offers=[...all.values()];data.offerCount=data.offers.length;if(clean.length){status.status='ok';status.count=clean.length;status.message=`${clean.length} valide Filialangebote über Netto-Reader`;status.transport='reader';}else{status.status='no_data';status.message=`Netto-Reader erreichbar, aber 0 valide Angebote (${md.length} Zeichen)`;status.transport='reader';}data.nettoReaderAt=now;await fs.writeFile(file,JSON.stringify(data,null,2)+'\n');console.log(`Netto Reader: ${clean.length} Angebote`);
