import test from 'node:test';
import assert from 'node:assert/strict';
import { normalizeOffer, comparable, relation } from './product-normalizer.js';

const cases = [
  ['Mini Windbeutel mit Sahnefüllung 250 g','Windbeutel'],
  ['TK Windbeutel mit Sahne 500 g','Windbeutel'],
  ['Windbeutelchen Vanille 200 g','Windbeutel'],
  ['Windbeutel Dessert 6 Stück','Windbeutel'],
  ['Windbeutel mit Schokosahne','Windbeutel'],
  ['babylove Windelbeutel 100 St.','Windelbeutel'],
  ['Windelbeutel mit Frischeduft 100 Stück','Windelbeutel'],
  ['Windelbeutel extra reißfest','Windelbeutel'],
  ['Windelbeutel Nachfüllpack','Windelbeutel'],
  ['Entsorgungs-Windelbeutel 50 St.','Windelbeutel'],
  ['Windelcreme sensitiv 75 ml','Windelcreme'],
  ['Baby Wundschutzcreme 100 ml','Windelcreme'],
  ['Wundschutz Creme Calendula','Windelcreme'],
  ['Schutzcreme für den Windelbereich','Windelcreme'],
  ['Windelcreme ohne Parfum','Windelcreme'],
  ['Windeleimer weiß','Windeleimer'],
  ['Windeleimer mit Deckel','Windeleimer'],
  ['Windeleimer Nachfüllsystem','Windeleimer'],
  ['Windeleimer geruchsdicht','Windeleimer'],
  ['Baby Windeleimer 20 l','Windeleimer'],
  ['Windelvlies 100 Blatt','Windelvlies'],
  ['Windelvlies Rolle','Windelvlies'],
  ['Windelvlies für Stoffwindeln','Windelvlies'],
  ['Öko Windelvlies 120 Blatt','Windelvlies'],
  ['Baby Windelvlies','Windelvlies'],
  ['Schwimmwindel Größe 3','Schwimmwindeln'],
  ['Schwimmwindeln Gr. 4','Schwimmwindeln'],
  ['Baby Schwimmwindel Größe 5','Schwimmwindeln'],
  ['Schwimmwindel Gr 6','Schwimmwindeln'],
  ['Einweg Schwimmwindel Größe 4','Schwimmwindeln'],
  ['Wickelunterlagen 10 Stück','Wickelunterlagen'],
  ['Wickelunterlage unterwegs','Wickelunterlagen'],
  ['Baby Wickelunterlagen 60x60','Wickelunterlagen'],
  ['Einmal Wickelunterlage','Wickelunterlagen'],
  ['Wickelunterlagen extra saugstark','Wickelunterlagen'],
  ['Baby Feuchttücher sensitiv','Feuchttücher'],
  ['Feuchttücher 80 Stück','Feuchttücher'],
  ['Babytücher ohne Parfum','Feuchttücher'],
  ['Baby Wipes sensitive','Feuchttücher'],
  ['Feuchttücher Aqua','Feuchttücher'],
  ['Baby-Waschlappen extra weich','Baby-Waschlappen'],
  ['Baby Waschlappen Baumwolle','Baby-Waschlappen'],
  ['Baby-Waschlappen 5 Stück','Baby-Waschlappen'],
  ['Windeln Größe 1, 2-5 kg','Windeln'],
  ['Pampers Windeln Gr. 4, 9-14 kg','Windeln'],
  ['Baby Dry Pants Größe 5, 11-17 kg','Windeln'],
  ['Windelhose Größe 6, 15-30 kg','Windeln'],
  ['Premium Windeln Größe 3, 6-10 kg','Windeln'],
  ['Zahnpasta Kariesschutz 75 ml','Zahnpasta'],
  ['Zahncreme sensitiv 75 ml','Zahnpasta'],
  ['Kinder Zahnpasta 50 ml','Zahnpasta'],
  ['Zahncreme Kräuter 100 ml','Zahnpasta'],
  ['Zahnpasta Whitening','Zahnpasta'],
  ['Zahnbürste mittel','Zahnbürste'],
  ['Elektrische Zahnbürste','Zahnbürste'],
  ['Kinder Zahnbürste weich','Zahnbürste'],
  ['Zahnbürste sensitiv','Zahnbürste'],
  ['Reise Zahnbürste','Zahnbürste'],
  ['Zahnseide gewachst 50 m','Zahnseide'],
  ['Zahnseide Mint 40 m','Zahnseide'],
  ['Zahnseide extra fein','Zahnseide'],
  ['Mundspülung Zahnfleischschutz','Mundspülung'],
  ['Mundwasser frisch 500 ml','Mundspülung'],
  ['Mundspülung sensitiv 500 ml','Mundspülung'],
  ['Zahnreinigungstabletten 30 St.','Zahnreinigungstabletten'],
  ['Gebissreiniger Tabs','Zahnreinigungstabletten'],
  ['Prothesenreiniger Tabletten','Zahnreinigungstabletten'],
  ['Spülmaschinentabs All in 1','Spülmaschinentabs'],
  ['Geschirrspültabs 40 Stück','Spülmaschinentabs'],
  ['Spülmaschinen Tabs Classic','Spülmaschinentabs'],
  ['Geschirrspültabletten 60 St.','Spülmaschinentabs'],
  ['Klarspüler 750 ml','Klarspüler'],
  ['Klarspüler Glanz 1 l','Klarspüler'],
  ['Spülmaschinensalz 2 kg','Spülmaschinensalz'],
  ['Regeneriersalz grob 1,5 kg','Spülmaschinensalz'],
  ['Spülmittel Zitrone 500 ml','Spülmittel'],
  ['Handspülmittel sensitiv 500 ml','Spülmittel'],
  ['Spülmittel Konzentrat 450 ml','Spülmittel'],
  ['Weichspüler Frische 50 WL','Weichspüler'],
  ['Weichspüler sensitiv 40 WL','Weichspüler'],
  ['Weichspüler Konzentrat 38 WL','Weichspüler'],
  ['Fleckentferner Spray 500 ml','Fleckentferner'],
  ['Fleckensalz 500 g','Fleckentferner'],
  ['Fleckenspray 750 ml','Fleckentferner'],
  ['Vollwaschmittel Pulver 20 WL','Waschmittel'],
  ['Colorwaschmittel flüssig 40 WL','Waschmittel'],
  ['Feinwaschmittel Gel 30 WL','Waschmittel'],
  ['Waschcaps Color 24 WL','Waschmittel'],
  ['Waschpods Universal 18 WL','Waschmittel'],
  ['Toilettenpapier 3-lagig 8 Rollen','Toilettenpapier'],
  ['Toilettenpapier Recycling 8 Rollen','Toilettenpapier'],
  ['Küchenpapier 4 Rollen','Küchenpapier'],
  ['Küchenrolle 3-lagig','Küchenpapier'],
  ['Taschentücher 30 Packungen','Taschentücher'],
  ['Taschentücher sensitiv','Taschentücher'],
  ['Kosmetiktücher Box 100 Stück','Kosmetiktücher'],
  ['Gesichtstücher ultrasoft','Kosmetiktücher'],
  ['Milchreis Original 200 g','Milchreis'],
  ['Milchreis Dessert Vanille 200 g','Milchreis'],
  ['Milchreis trocken 500 g','Milchreis'],
  ['Vollmilchschokolade 100 g','Milchschokolade'],
  ['Milchschokolade Alpen 100 g','Milchschokolade'],
  ['Schokomilch 500 ml','Schokomilch'],
  ['Kakaomilch 1 l','Schokomilch'],
  ['Milchbrötchen 8 Stück','Milchbrötchen'],
  ['Mini Milchbrötchen','Milchbrötchen'],
  ['Kokosmilch 400 ml','Kokosmilch'],
  ['Bio Kokosmilch 400 ml','Kokosmilch'],
  ['Kondensmilch 7,5 % 340 g','Kondensmilch'],
  ['Kaffeesahne 10 % 200 g','Kondensmilch'],
  ['Milchpulver 500 g','Milchpulver'],
  ['Magermilchpulver 250 g','Milchpulver'],
  ['PRE Anfangsmilch 800 g','Babymilch'],
  ['Folgemilch 2 800 g','Babymilch'],
  ['Kindermilch 1+ 600 g','Babymilch'],
  ['Säuglingsnahrung PRE 600 g','Babymilch'],
  ['Frische Vollmilch 3,5 % 1 l','Milch'],
  ['H-Milch 3,5 % 1 l','Milch'],
  ['Fettarme Milch 1,5 % 1 l','Milch'],
  ['Bergbauern Milch 3,5 %','Milch'],
  ['Weidemilch 3,8 % 1 l','Milch'],
  ['Butterkeks 200 g','Butterkeks'],
  ['Butterkekse klassisch 250 g','Butterkeks'],
  ['Erdnussbutter crunchy 350 g','Erdnussbutter'],
  ['Erdnussbutter creamy 350 g','Erdnussbutter'],
  ['Kakaobutter 100 g','Kakaobutter'],
  ['Kräuterbutter 100 g','Kräuterbutter'],
  ['Butterschmalz 250 g','Butterschmalz'],
  ['Deutsche Markenbutter 250 g','Butter'],
  ['Süßrahmbutter 250 g','Butter'],
  ['Sauerrahmbutter 250 g','Butter'],
  ['Katzenfutter Nassfutter 400 g','Tierfutter'],
  ['Katzenfutter Trockenfutter 1 kg','Tierfutter'],
  ['Hundefutter Nassfutter 800 g','Tierfutter'],
  ['Hundefutter Trockenfutter 2 kg','Tierfutter']
];

const offer = (name, store='A') => normalizeOffer({
  name, store, market: store, size:'1 St.', price:1.99, unit:1.99, unitLabel:'€/Stk.'
});

test('mindestens 100 zusätzliche semantische Edge-Cases sind klassifiziert', () => {
  assert.ok(cases.length >= 100, `Nur ${cases.length} Edge-Cases vorhanden`);
  for (const [name, expected] of cases) {
    const actual = offer(name).semanticType;
    assert.equal(actual, expected, `Falscher Produkttyp für "${name}": ${actual} statt ${expected}`);
  }
});

const forbiddenPairs = [
  ['Windbeutel','Windelbeutel'],
  ['Windbeutel','Windeln Größe 4, 9-14 kg'],
  ['Windelbeutel','Windeln Größe 4, 9-14 kg'],
  ['Windeln Größe 4, 9-14 kg','Windelcreme'],
  ['Windeln Größe 4, 9-14 kg','Windeleimer'],
  ['Windeln Größe 4, 9-14 kg','Windelvlies'],
  ['Windeln Größe 4, 9-14 kg','Feuchttücher'],
  ['Windeln Größe 4, 9-14 kg','Wickelunterlagen'],
  ['Windeln Größe 4, 9-14 kg','Schwimmwindel Größe 4'],
  ['Windeln Größe 1, 2-5 kg','Windeln Größe 6, 15-30 kg'],
  ['Milch 3,5 %','Milchreis Original'],
  ['Milch 3,5 %','Vollmilchschokolade'],
  ['Milch 3,5 %','Kokosmilch'],
  ['Milch 3,5 %','PRE Anfangsmilch'],
  ['Milch 3,5 %','Kondensmilch'],
  ['Milch 3,5 %','Milchpulver'],
  ['Butter','Butterkeks'],
  ['Butter','Erdnussbutter'],
  ['Butter','Kakaobutter'],
  ['Zahnpasta','Zahnbürste'],
  ['Zahnpasta','Zahnseide'],
  ['Zahnpasta','Mundspülung'],
  ['Spülmittel','Spülmaschinentabs'],
  ['Spülmittel','Klarspüler'],
  ['Spülmaschinentabs','Spülmaschinensalz'],
  ['Waschmittel Pulver','Weichspüler'],
  ['Waschmittel Pulver','Fleckentferner'],
  ['Toilettenpapier','Küchenpapier'],
  ['Toilettenpapier','Taschentücher'],
  ['Küchenpapier','Kosmetiktücher'],
  ['Katzenfutter Nassfutter','Hundefutter Nassfutter'],
  ['Katzenfutter Nassfutter','Katzenfutter Trockenfutter']
];

test('funktional verschiedene Produkte bleiben auch bei identischer künstlicher Preiseinheit unvergleichbar', () => {
  for (const [left, right] of forbiddenPairs) {
    const a=offer(left,'Markt A');
    const b=offer(right,'Markt B');
    assert.equal(comparable(a,b), false, `Falsch vergleichbar: "${left}" <> "${right}"`);
    assert.notEqual(relation(a,b), 'exact_match', `Fälschliches exact_match: "${left}" <> "${right}"`);
  }
});
